Repository JacquesCarette/Drasil, pull requests merged in 2019-06, with the labels that each got.

#1542 PR - Correcting Final Hlint warnings
  code/.hlint.yaml
  code/drasil-example/Drasil/GamePhysics/DataDefs.hs
  code/drasil-example/Drasil/GlassBR/TMods.hs
  code/drasil-example/Drasil/NoPCM/Assumptions.hs
  code/drasil-example/Drasil/NoPCM/GenDefs.hs
  code/drasil-example/Drasil/NoPCM/Requirements.hs
  code/drasil-example/Drasil/SWHS/GenDefs.hs
  code/drasil-example/Drasil/SWHS/IMods.hs
  code/drasil-example/Drasil/SWHS/Requirements.hs
  code/website/site.hs
Labels: CI: HLint

#1546 [Small PR] Finished HLint
  code/drasil-data/Data/Drasil/Quantities/Physics.hs
  code/drasil-example/Drasil/GamePhysics/DataDefs.hs
Labels: High Priority

#1545 New module Potential Energy in datadefs.hs
  code/drasil-data/Data/Drasil/Concepts/Physics.hs
  code/drasil-data/Data/Drasil/Quantities/Physics.hs
  code/drasil-example/Drasil/GamePhysics/DataDefs.hs
  code/drasil-example/Drasil/GamePhysics/Unitals.hs
  code/stable/gamephys/SRS/Chipmunk_SRS.tex
  code/stable/gamephys/Website/Chipmunk_SRS.html
Labels: CI: HLint

#1544 Finish drasil-utils
  code/drasil-data/Data/Drasil/README.md
  code/drasil-data/Data/Drasil/SentenceStructures.hs
  code/drasil-data/drasil-data.cabal
  code/drasil-docLang/Drasil/Sections/Introduction.hs
  code/drasil-docLang/Drasil/Sections/Requirements.hs
  code/drasil-docLang/Drasil/Sections/TraceabilityMandGs.hs
  code/drasil-example/Drasil/GamePhysics/Body.hs
  code/drasil-example/Drasil/GamePhysics/Changes.hs
  code/drasil-example/Drasil/GlassBR/Body.hs
  code/drasil-example/Drasil/GlassBR/Changes.hs
  code/drasil-example/Drasil/GlassBR/Figures.hs
  code/drasil-example/Drasil/GlassBR/Requirements.hs
  code/drasil-example/Drasil/GlassBR/Unitals.hs
  code/drasil-example/Drasil/NoPCM/Body.hs
  code/drasil-example/Drasil/NoPCM/Changes.hs
  code/drasil-example/Drasil/NoPCM/Unitals.hs
  code/drasil-example/Drasil/SSP/Changes.hs
  code/drasil-example/Drasil/SSP/GenDefs.hs
  code/drasil-example/Drasil/SSP/IMods.hs
  code/drasil-example/Drasil/SSP/TMods.hs
  code/drasil-example/Drasil/SWHS/Body.hs
  code/drasil-example/Drasil/SWHS/Changes.hs
  code/drasil-example/Drasil/SWHS/DataDefs.hs
  code/drasil-example/Drasil/SWHS/DataDesc.hs
  code/drasil-example/Drasil/SWHS/GenDefs.hs
  code/drasil-example/Drasil/SWHS/Requirements.hs
  code/drasil-example/Drasil/SWHS/Unitals.hs
  code/drasil-utils/Utils/Drasil.hs
  code/drasil-utils/Utils/Drasil/Misc.hs
  code/stable/gamephys/SRS/Chipmunk_SRS.tex
  code/stable/gamephys/Website/Chipmunk_SRS.html
  code/stable/glassbr/SRS/GlassBR_SRS.tex
  code/stable/glassbr/Website/GlassBR_SRS.html
  code/stable/nopcm/SRS/NoPCM_SRS.tex
  code/stable/nopcm/Website/NoPCM_SRS.html
  code/stable/ssp/SRS/SSP_SRS.tex
  code/stable/ssp/Website/SSP_SRS.html
  code/stable/swhs/SRS/SWHS_SRS.tex
  code/stable/swhs/Website/SWHS_SRS.html
Labels: CI: HLint

#1600 Goals Take [ConceptInstance]
  code/drasil-docLang/Drasil/DocLang.hs
  code/drasil-docLang/Drasil/DocumentLanguage.hs
  code/drasil-docLang/Drasil/ExtractDocDesc.hs
  code/drasil-example/Drasil/GamePhysics/Body.hs
  code/drasil-example/Drasil/GlassBR/Body.hs
  code/drasil-example/Drasil/NoPCM/Body.hs
  code/drasil-example/Drasil/SSP/Body.hs
  code/drasil-example/Drasil/SSP/IMods.hs
  code/drasil-example/Drasil/SWHS/Body.hs
  code/stable/glassbr/SRS/GlassBR_SRS.tex
  code/stable/glassbr/Website/GlassBR_SRS.html
Labels: Low Priority

#1604 Automate Physical System Description
  code/drasil-docLang/Drasil/DocLang.hs
  code/drasil-docLang/Drasil/DocumentLanguage.hs
  code/drasil-docLang/Drasil/DocumentLanguage/Labels.hs
  code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs
  code/drasil-example/Drasil/GlassBR/Body.hs
  code/drasil-example/Drasil/NoPCM/Body.hs
  code/drasil-example/Drasil/SSP/Body.hs
  code/drasil-example/Drasil/SWHS/Body.hs
  code/stable/ssp/SRS/SSP_SRS.tex
  code/stable/ssp/Website/SSP_SRS.html
Labels: Low Priority
